### ISSUE TITLE
SDG数据集

### ISSUE THREAD

**Issue by peng913** [suntea233/DualLoRA#5]
尊敬的作者：
       您好！
       我按照您的建议，完成SDG数据集的复现。
       （1）想跟您确认，您的输出结果是否是如图所呈现
![SDG](https://github.com/user-attachments/assets/692cc0be-e2ad-451c-a3d7-3bc693c884bb)
      （2）论文中的关于SDG数据集的JGA(%)/AGA(%)指标，我在您的baseline,prompter论文上并未找到AGA(%)指标，想知道
JGA(%)/AGA(%)是不是按上图内容中所展示的，如BusesJGA(%)= （Buses_3-additional_luggage 0.75409+Buses_3-category 0.63869+
Buses_3-departure_date 0.69454+Buses_3-departure_time 0.87782+Buses_3-from_city 0.78988+Buses_3-from_station 0+Buses_3-num_passengers 0.7473+Buses_3-price 0+ Buses_3-to_city 0.70842+Buses_3-to_station [0/9=52.1](url)

**Comment by suntea233** [comment]
您好，我们在SGD上的实验评估是按照prompter中所提供的[sgd_eval.sh](https://github.com/cuthalionn/Prompter/blob/main/scripts/sgd_eval.sh)得到的结果

**Comment by peng913** [comment]
按照您的帮助我修改了sgd_eval.sh文件，
PRED="./save/t5-2024-11-30-16-20-train-normal/results"
DSTC8="./data/dstc8-schema-guided-dialogue"
EVAL_SET="test"
echo $PRED
python SGD_eval_script.py --prediction_dir $PRED --dstc8_data_dir $DSTC8 --eval_set $EVAL_SET --output_metric_file ${PRED}/"result.json"
不幸的是出现了Traceback (most recent call last): File "/root/DualLoRA-main/SGD_eval_script.py", line 26, in <module> import tensorflow.compat.v1 as tf File "/root/miniconda3/envs/duallora/lib/python3.9/site-packages/tensorflow/__init__.py", line 49, in <module> from tensorflow._api.v2 import __internal__ File "/root/miniconda3/envs/duallora/lib/python3.9/site-packages/tensorflow/_api/v2/__internal__/__init__.py", line 8, in <module> from tensorflow._api.v2.__internal__ import autograph File "/root/miniconda3/envs/duallora/lib/python3.9/site-packages/tensorflow/_api/v2/__internal__/autograph/__init__.py", line 8, in <module> from tensorflow.python.autograph.core.ag_ctx import control_status_ctx # line: 34 File "/root/miniconda3/envs/duallora/lib/python3.9/site-packages/tensorflow/python/autograph/core/ag_ctx.py", line 21, in <module> from tensorflow.python.autograph.utils import ag_logging File "/root/miniconda3/envs/duallora/lib/python3.9/site-packages/tensorflow/pyth您能给我一些建议或者告诉我怎么您是怎么运行sgd_eval.sh的
